CREATE TABLE ROUTE(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  CONDITION VARCHAR(255),
  DISTANCE DOUBLE
);

CREATE TABLE tblAthlete(
  ATHLETE_ID INT AUTO_INCREMENT,
  EMAIL_ADDRESS VARCHAR(255),
  FULL_NAME VARCHAR(2000),
  GIVEN_NAME VARCHAR(2000),
  DATE_OF_BIRTH DATE,
  CITY VARCHAR(2000),
  COUNTRY VARCHAR(2000),
  PASSWORD VARCHAR(2000),
  SALT VARCHAR(2000)
);